Neste Trabalho do Bootcamp de Ciência de Dados da DIO vou usar uma base de dados pública referente a lista de nomes de bebês registrados nos EUA em 2019 para fazer um ETL simples.

CSV disponível neste link : https://docs.google.com/spreadsheets/d/1-W6BITJnUabMEbeMlo6Lv0qZ5AY79rMAfMlBENrC_NM/edit?usp=sharing

# Extração :

In [ ]:
import pandas as pd

nomes = pd.read_csv("nomes.csv")

display(nomes)

           name gender  count
0        Olivia      F  18451
1          Emma      F  17102
2           Ava      F  14440
3        Sophia      F  13714
4      Isabella      F  13306
...         ...    ...    ...
31949    Zyheem      M      5
31950     Zykel      M      5
31951    Zyking      M      5
31952       Zyn      M      5
31953     Zyran      M      5

[31954 rows x 3 columns]

# Transformação:

In [ ]:
'''
Aqui eu coloco os dados da coluna count em ordem decrescente
de uma forma que independe do gênero da pessoa e coloco filtro para os
10 nomes mais registrados

'''
ordemdecrescente = nomes.sort_values('count', ascending=False).head(10)

# Agora crio uma tabela em ordem alfabética

alpha = nomes.sort_values('name')

# Carregamento:

Agora eu crio novos arquivos CSV com a tabela transformada

In [ ]:
# Os dez nomes mais usados independente do Sexo

ordemdecrescente.to_csv('emordem.csv')

In [ ]:
# Em Ordem alfabética

alpha.to_csv('alpha.csv')